stages:
  - build
  - deploy

variables:
  APPLICATION_NAME: whereabouts-front
  CONTAINER_TAG: ${CI_COMMIT_SHORT_SHA}
  CONTAINER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CONTAINER_TAG}

image: moreillon/ci-dind:4bca50d7
services:
  - name: docker:19.03.12-dind

build:
  stage: build
  before_script:
    # Docker hub login
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
  script:
    # Buikd and push container image
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_TAGGED}
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_LATEST}

deploy:
  stage: deploy
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
  environment:
    name: production
    kubernetes:
      # Obtained from GitLab
      namespace: ${KUBERNETES_NAMESPACE}
