apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
<<<<<<< kubernetes_manifest.yml
        - name: ${APPLICATION_NAME}
          image: ${CONTAINER_IMAGE_TAGGED}
          ports:
            - containerPort: 80
          # Get environment variables from secret
          envFrom:
            - secretRef:
                name: environment-variables
=======
      - name: ${APPLICATION_NAME}
        image: ${CONTAINER_IMAGE_TAGGED}
        ports:
        - containerPort: 80
        # Get environment variables from secret
        envFrom:
        - secretRef:
           name: environment-variables
      imagePullSecrets:
      - name: ${K8S_ECR_SECRET_NAME}

>>>>>>> kubernetes_manifest.yml
---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  type: NodePort
  selector:
    app: ${APPLICATION_NAME}
  ports:
    - port: 80
      nodePort: ${K8S_SERVICE_PORT}
